language: php

before_script:
  - ./tests/travis/init.sh
  - composer update --dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - memcached
  - redis-server

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - php vendor/bin/phpunit --configuration phpunit.xml.travisci --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
